<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    
    <!-- NuGet Metadata -->
    <PackageId>Tedd.TUI</PackageId>
    <Authors>Tedd</Authors>
    <Description>Cross-Platform TUI Framework for .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>tui;console;terminal;gui;wpf</PackageTags>
    <RepositoryUrl>https://github.com/Tedd/Tedd.TUI</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Tedd.TUI.Benchmarks</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Tedd.TUI.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
